[package]
name = "pi"
version = "0.1.0"
edition = "2021"
default-run = "pi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
exitcode = "1.1.2"
rug = "1.15.0"
rayon = "1.5.1"